name: Deploy
on: [push, pull_request]
jobs:
  build:
    name: Build and Test Images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/hub-duncdrum' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' || github.base_ref ==  'develop' || github.base_ref ==  'master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Make buildkit default
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true    
      - name: Install bats
        run: sudo apt-get install bats
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build images
        run: mvn -V -B -q -Pdocker -DskipTests -Ddependency-check.skip=true clean package
      - name: Check local images
        run: docker image ls     
      - name: Start container
        run: |
          docker run -dit -p 8080:8080 --name exist-ci --rm duncdrum/exist-docker:latest
          sleep 35s
      - name: Run tests
        run: bats --tap exist-docker/src/test/bats/*.bats
      # NOTE (DP): The below will publish an experimentally tagged image from any PR into develop.
      # Useful when working on features / debugging
      - name: Push experimental images
        if: github.base_ref == 'develop' || github.ref == 'refs/heads/hub-duncdrum' 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: mvn -Ddocker.tag=experimental -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD docker:build docker:push
        working-directory: ./exist-docker  
  
